### ISSUE TITLE
Restricted contract details

### ISSUE THREAD

**Issue by XwayTomy** [martinjonsson01/contract-portal#100]
## Description
As a discount manager I want potential customers to not be able to acces the detailed contract view, so that they feel an urge to subscribe to my service.

## Acceptance criteria
- [x] When a non logged in user tries to click on a contract card, they get prompted to sign up to access the details.
- [x] Non-logged in users can access the contracts page and the about us page
- [x] The contract cards on the contract page should be distributed horisontally on the page

## Dependencies
- #26

**Comment by jonathan-lindqvist** [comment]
Since this story makes changes to the contract and about us pages, then those pages should be styled accordingly
