### ISSUE TITLE
About Us - Page

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#12]
## Description
As a stakeholder I want to present the company's values and policies to be transparent and inform our customers.

## Acceptance criteria
- [x] Able to navigate to the About Us page
- [x] Contains text the stakeholder wants to show
- [x] Contains relevant images the stakeholder wants to show

## Dependencies
- #8

**Comment by XwayTomy** [comment]
**Text:** Vi har arbetat med inköp i över 10 år och har gedigen kunskap av kategori- och leverantörsstyrning. Vi har en stor passion för inköp och förstklassig service, så att du som kund kan spara tid och sänka era kostnader. Genom oss får ni tillgång till unika avtal och effektiva processer. Vi arbetar självklart med arbetssätt som bidrar till att ni kan nå era hållbarhetsmål med effektiva verktyg för både miljö och CSR. Det viktigaste för oss är att vi kan hjälpa till i våra kunders liv, där det verkligen behövs. Vi vill därför erbjuda dig som kund förstklassig service och prioriterar varje kundrelation så att du kan känna dig trygg i våra händer.
