### ISSUE TITLE
Bug: Admin page access

### ISSUE THREAD

**Issue by JacobBredin** [martinjonsson01/contract-portal#124]
Reproduce bug:
When logged in as an admin on the admin page and the page is refreshed, the admin page is still shown, even though the user is logged out.

**Comment by martinjonsson01** [comment]
This bug is no longer possible as described with the implementation of #120 redirecting the user to the welcome page after logging them out.

What is still possible, though, is manually navigating to `/admin` and being able to view (although not being able to do anything) the empty input forms.
