### ISSUE TITLE
Resize contract cards

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#159]
## Description
As a customer I want the contract cards to be smaller, so that I can view more of them at once.

## Acceptance criteria
- [x] On a 13" laptop screen, 4 columns (no more than 4) of cards are visible
- [x] Two rows of cards should be visible on a 13" laptop screen (given enough contracts in the database)
- [x] Take a look at spacing

**Comment by JacobBredin** [comment]
> How come?

Nevermind, I thought you made larger changes to the HTML code of the contract than you did.

**Comment by martinjonsson01** [comment]
> I thought you made larger changes to the HTML code of the contract than you did.

Ah, yeah I mostly reformatted it so the lines weren't 800 characters long 😝

**Comment by JacobBredin** [comment]
Is it overkill to refactor some of the code, seems like a lot of copy and paste right now?

**Comment by martinjonsson01** [comment]
Refactor what? The styling?

**Comment by JacobBredin** [comment]
Inside ContractCard there are 4 divs that handle onclick addToRecentlyViewed, there must be some better way of doing that.
