### ISSUE TITLE
Adding contract data from admin page

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#17]
## Description
As an admin I want to be able to add contract data because I want it to be easier to add information about discounts.

## Acceptance criteria
- [x] An admin can input a title in the admin page
- [x] An admin can input an image in the admin page
- [x] An admin can input a description of the contract in the admin page
- [x] An admin can input usage instructions in the admin page
- [x] An admin can submit the data and have it persist

## Dependencies
- #29

**Comment by JacobBredin** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server
