### ISSUE TITLE
Contract Detail View

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#47]
## Description
As a purchaser I want to see details about a contract in order to utilize discount.

## Acceptance criteria
- [x] When a contract card is clicked, a details view is shown
- [x] The details view contains (in Swedish):
  - [x] A contract image
  - [x] A contract name
  - [x] How to utilize the discount
  - [x] A description of the discount
  - [x] Contact info for the supplier
  - [x] Text about the supplier
  - [x] Show file download links
  - [x] There is a close button
- [x] An inspirational image is shown along with the contract
- [x] An admin can create clickable links in "How to utilize" text box

## Dependencies
- #30

**Comment by XwayTomy** [comment]
There would be a need to be able to add clickable links under the header "How to utilize the discount"

**Comment by martinjonsson01** [comment]
[Library](https://github.com/Megabit/Blazorise) that contains component for markdown editor.

[Library](https://github.com/xoofx/markdig) for rendering markdown in C#.
