### ISSUE TITLE
Design website layout

### ISSUE THREAD

**Issue by martinjonsson01** [martinjonsson01/contract-portal#9]
## Description
As a team member I want a common design layout because I want something to follow and show our stakeholder.

## Acceptance criteria
- [x] Dashboard has a layout
- [x] About Us has a layout
- [x] Admin Page (first version) has a layout
- [x] Contracts Page has a layout

**Comment by Gigset** [comment]
Jag tycker det ser bra ut! Lite fundersam på vad som är tänkt med "leveransproblem" på dashboarden.
[https://www.figma.com/file/3UPvMc1hgvkRYx1qN8mDW1/Contract-Portal?node-id=0%3A1](url)
