### ISSUE TITLE
Adding Analytics tools

### ISSUE THREAD

**Issue by XwayTomy** [martinjonsson01/contract-portal#98]
## Description
As a contract manager i want to be able to see the tracked information about my customers behavior so that i can adapt my actions to receive the best results possible.

## Acceptance criteria
- [x] Set up a connection to Google Analaytics for the project
- [x] There is a link to Google on the admin-page that lets you see all collected data.

**Comment by martinjonsson01** [comment]
This and #99 are currently too horisontal, and should instead (ideally) be split into very small vertical slices.
